#! /bin/bash

#API Paramaters
JamfProURL="Null" #URL of Jamf Pro Server
username="Null"									#username of account with privilges for writing to Jamf Pro
password="Null"									#password of account with priviliges for writing to Jamf Pro

#Parameters
scopeGroupID="Null" 								#smart group ID that will hold nested groups for initial deployment
exclusionGroupID="Null" 							#Static group ID to add devices to for exclusions
fileName="Null" 							#local filename of CSV holding restricted software entries

#RestrictedSoftware Additional Parameters
send_notification="false"						#send email notification when this triggers?
kill_process="true"								#kill process when triggered?
delete_executable="true"						#delete executable binary when triggered?

#message to display AFTER name listed in CSV
display_message_part=" is not authorized for use on Hashicorp corporate-owned assets. Please contact the Help Desk for more information. " 

#Pull info from CSV line by line.
while IFS="," read -r rec_column1 rec_column2 rec_column3 rec_column4
do
post="<restricted_software>
	<general>
		<name>$rec_column1</name>
		<process_name>$rec_column2</process_name>
		<match_exact_process_name>$rec_column4</match_exact_process_name>
		<send_notification>$send_notification</send_notification>
		<kill_process>$kill_process</kill_process>
		<delete_executable>$delete_executable</delete_executable>
		<display_message>$rec_column3$display_message_part</display_message>
		<site>
			<id>-1</id>
			<name>None</name>
		</site>
	</general>
	<scope>
		<all_computers>false</all_computers>
		<computers/>
		<computer_groups>
 			<computer_group>
            	<id>$scopeGroupID</id>
        	</computer_group>
		</computer_groups>
		<buildings/>
		<departments/>
		<exclusions>
			<computers/>
		<computer_groups>
 			<computer_group>
            	<id>$exclusionGroupID</id>
        	</computer_group>
		</computer_groups>
			<buildings/>
			<departments/>
			<users/>
		</exclusions>
	</scope>
</restricted_software>"

#attempt to post new restricted software entry based on current data
/usr/bin/curl -u "$username:$password" --basic -L "$JamfProURL/JSSResource/restrictedsoftware/id/:0" -H 'Accept: application/xml' -H 'Content-Type: application/xml' -d "$post"
#echo "$post" #debug
 done < <(tail -n +2 ${fileName})